// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGecS_a1WUKS92lmlJi1PLXLKSdCKvNxc',
    appId: '1:677834212397:web:2fcbc2b807e6de031ae4a4',
    messagingSenderId: '677834212397',
    projectId: 'dna-taskflow-prime',
    authDomain: 'dna-taskflow-prime.firebaseapp.com',
    storageBucket: 'dna-taskflow-prime.firebasestorage.app',
    measurementId: 'G-T33MMV09T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmCMsAkJSfyQkMgZWtECW6DcDFFD2iCWg',
    appId: '1:677834212397:android:185a40e00181430b1ae4a4',
    messagingSenderId: '677834212397',
    projectId: 'dna-taskflow-prime',
    storageBucket: 'dna-taskflow-prime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs9zzWixOx-eEfAJOpuLbYXZhxQuPYYBc',
    appId: '1:677834212397:ios:f03f54ec77bd0ccb1ae4a4',
    messagingSenderId: '677834212397',
    projectId: 'dna-taskflow-prime',
    storageBucket: 'dna-taskflow-prime.firebasestorage.app',
    iosBundleId: 'com.example.dnaTaskflowPrime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs9zzWixOx-eEfAJOpuLbYXZhxQuPYYBc',
    appId: '1:677834212397:ios:f03f54ec77bd0ccb1ae4a4',
    messagingSenderId: '677834212397',
    projectId: 'dna-taskflow-prime',
    storageBucket: 'dna-taskflow-prime.firebasestorage.app',
    iosBundleId: 'com.example.dnaTaskflowPrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGecS_a1WUKS92lmlJi1PLXLKSdCKvNxc',
    appId: '1:677834212397:web:ee452cf3db4485f61ae4a4',
    messagingSenderId: '677834212397',
    projectId: 'dna-taskflow-prime',
    authDomain: 'dna-taskflow-prime.firebaseapp.com',
    storageBucket: 'dna-taskflow-prime.firebasestorage.app',
    measurementId: 'G-ENV704WCHG',
  );
}
